// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type Card struct {
	ID            string
	ProjectSlug   string
	Number        int64
	Title         string
	Status        string
	ColumnName    string
	Deleted       int64
	CreatedAt     string
	UpdatedAt     string
	CommentsCount int64
	HistoryCount  int64
}

type Project struct {
	Slug        string
	Name        string
	LocalPath   sql.NullString
	RemoteUrl   sql.NullString
	NextCardSeq int64
	CreatedAt   string
	UpdatedAt   string
}
